language: node_js
node_js: 12
install:
- npm install
script:
- npm run docs:build

addons:
  ssh_known_hosts:
  - 60.205.179.50
before_install:
- openssl aes-256-cbc -K $encrypted_8e3301ed1bb3_key -iv $encrypted_8e3301ed1bb3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  # 配置一下权限和主机认证使用的秘钥文件：
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 主机IP地址\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- scp -o stricthostkeychecking=no -r docs root@60.205.179.50:/www/server/tomcat/webapps/vary_blogs

notifications:
  email:
  - haoc43054@gmail.com